### ISSUE TITLE
Clip Bug

### ISSUE THREAD

**Issue by aure** [PaulBatchelor/Soundpipe#67]
This is a bug originally discovered by Joshua-Thompson on this [AudioKit Issue](https://github.com/audiokit/AudioKit/issues/340) and I believe it is a bug in Soundpipe as I'm able to reproduce it using the Sporth code:

`60 mtof 1 bltriangle
0.4 clip`

It appears the clip actually raises the volume of the triangle before clipping it.  

![screen shot 2016-04-09 at 5 49 57 pm](https://cloud.githubusercontent.com/assets/13122/14407791/5fb43190-fe8a-11e5-8981-8b25fd9a0ea0.png)

**Comment by PaulBatchelor** [comment]
By default, clip is set to the "sine method" of clipping (mode 1): the procedure is seen here:

https://github.com/PaulBatchelor/Soundpipe/blob/master/modules/clip.c#L86

In the Sporth code, I removed the ability to change the method, so that is what it using. It's possible that in this particular instance, the sine method may be causing this? I believe I ported it correctly from Csound:

https://github.com/csound/csound/blob/develop/Opcodes/pitch.c#L1599

I will look at this further, and see if I can generate these plots.

**Comment by PaulBatchelor** [comment]
Here is a plot I made in octave and Sporth comparing the clipped signal and the non clipped signal. I have also added the limiting points as straight lines:
 
![graph](https://cloud.githubusercontent.com/assets/8139389/14407876/8b83a5ae-fe8e-11e5-8384-91fdbf1ee156.png)

The sporth code is as follows:

```
60 mtof 1 bltriangle 0.4 clip
60 mtof 1 bltriangle 
0.4
-0.4

```

And the command I used to generate the plot:

```
sporth -c 4 -d 1000 -b plot debug.sp > out.m
octave --no-gui out.m
```

I am not sure what is causes that weird "hat" on the triangle wave.

**Comment by PaulBatchelor** [comment]
I believe this is intended behavior because you are actually applying a sine transformation to the signal under the threshold. I'd be willing to bet that this waveform looks worse than it sounds. This is actually a really good example of the way soft clipping distorts a signal. 

If you're really after some hard clipping to cleanly trim the peaks off, you could use the max/min functions in Sporth. Here's a plot comparing the signals:

![graph](https://cloud.githubusercontent.com/assets/8139389/14407912/faeb430a-fe90-11e5-8bae-936682678c82.png)

And the code...

```
60 mtof 1 bltriangle 0.4 min -0.4 max
60 mtof 1 bltriangle 

```

**Comment by aure** [comment]
Well, hold on before you say you won't fix.  Since Sporth does not implement the mode, we need to check it on hte Soundpipe level because a triangle sent through clip with the following parameters is what started this investigation:

triangle.amplitude = 0.5
clipper.limit = 0.4
clipper.clippingStartPoint = 0.3
clipper.method = 0 

![screen shot 2016-04-09 at 9 06 15 pm](https://cloud.githubusercontent.com/assets/13122/14408027/f05292e4-fe96-11e5-82ad-7da0c4331b0e.png)

**Comment by PaulBatchelor** [comment]
Huh.

It looks like they changed the clip code substantially in Csound since I
last ported the opcode..

Aure: 1 Paul: 0

I'll apply their changes. Sorry about that.

-P

**Comment by aure** [comment]
If we're keeping count it might be Aure: 1 Paul: 35

**Comment by PaulBatchelor** [comment]
I was on my phone when I was looking at the CSound code. I was looking at the wrong part.

I have pretty much copied the code verbatim (minus taking it out of the for loop). Feel free to compare the code yourself, maybe I missed something:

https://github.com/PaulBatchelor/Soundpipe/blob/master/modules/clip.c#L69
https://github.com/csound/csound/blob/develop/Opcodes/pitch.c#L1582

It could be that this is just what the algorithm does to the signal?

**Comment by aure** [comment]
Here's csound's clip acting on a triangle:

`<CsoundSynthesizer>
<CsOptions>
; Select audio/midi flags here according to platform
-odac     ;;;RT audio out
;-iadc    ;;;uncomment -iadc if RT audio input is needed too
; For Non-realtime ouput leave only the line below:
; -o clip.wav -W ;;; for file output any platform
</CsOptions>
<CsInstruments>

sr = 44100
ksmps = 32
nchnls = 2
0dbfs = 1

instr 1	
a1 vco 1, 440, 3, 0.5
   outs a1, a1

endin

instr 2	

avco vco 1, 440, 3, 0.5
a1 clip avco, 0, 0.4, 0.3
   outs a1, a1

endin

</CsInstruments>
<CsScore>
f 1 0 65536 10 1

; Play Instrument #1 for one second.
i 1 0 1
; Play Instrument #2 for one second.
i 2 1 1
e

</CsScore>
</CsoundSynthesizer>
![screen shot 2016-04-09 at 10 03 56 pm](https://cloud.githubusercontent.com/assets/13122/14408201/07ef7568-fe9f-11e5-9d1a-1ff26cb89423.png)
`

**Comment by PaulBatchelor** [comment]
Alrighty... that is odd. Will try to do the equivalent in Soundpipe, and see what happens there...

**Comment by PaulBatchelor** [comment]
This is the junk I get when I put a render bltriangle wave through clip-in-csound via diskin2:

![tri](https://cloud.githubusercontent.com/assets/8139389/14408269/b2aaf66a-fea1-11e5-808a-ddea8361f6da.png)

Now there's another possible error: bltriangle is being weird.

**Comment by PaulBatchelor** [comment]
Okay, this produces errors on valgrind. Now we're getting somewhere. I think there's some uninitialized variable somewhere:

```
#include <stdio.h>
#include "soundpipe.h"

typedef struct {
    sp_bltriangle *tri;
    sp_clip *clp;
} UserData;

void write_clip(sp_data *sp, void *ud) {
    UserData *udp = ud;
    SPFLOAT out, tri;
    sp_bltriangle_compute(sp, udp->tri, NULL, &tri);
    sp_clip_compute(sp, udp->clp, &tri, &out);
    sp->out[0] = out;
}

int main() {
    UserData ud;
    sp_data *sp;
    sp_create(&sp);

    sp_bltriangle_create(&ud.tri);
    sp_clip_create(&ud.clp);

    sp_clip_init(sp, ud.clp);
    ud.clp->lim = 0.4;
    ud.clp->meth = 0;
    sp_bltriangle_init(sp, ud.tri);
    *ud.tri->amp = 1.0;
    sp_process(sp, &ud, write_clip);

    sp_clip_destroy(&ud.clp);
    sp_bltriangle_destroy(&ud.tri);

    sp_destroy(&sp);
    return 0;
}

```

**Comment by PaulBatchelor** [comment]
Looks like I might have fixed it?

![smooooth](https://cloud.githubusercontent.com/assets/8139389/14408323/b450c244-fea4-11e5-8910-4d6fdf83bcdd.png)

I have pushed these changes to dev. Can you confirm this?

**Comment by PaulBatchelor** [comment]
I believe this issue may have started after commit e72a45 when I removed method as a parameter for the init function. Ooops.

**Comment by aure** [comment]
I can confirm that this works as advertised on Soundpipe, but I still have issues on AK, so I will leave that issue open but close this one.
